In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root / "src"))

import pandas as pd

from member3_preprocess import (
  clean_text,
  preprocess_dataframe,
  show_examples,
  TextPreprocessor
)

In [2]:
train_df = pd.read_csv("../data/raw/dataset_C_train.csv")
val_df = pd.read_csv("../data/raw/dataset_C_val.csv")

train_df.head()

,text,label_1,label_2,label_3,label_4
0,thanks status content fix warning review pleas...,1,1,1,1
1,account system error reply content,0,1,0,1
2,reply error info account content update notice...,0,1,0,0
3,delay status access content access urgent repl...,0,0,0,0
4,reply please feedback feedback system delay re...,0,0,1,0

Check dataset columns and size

In [3]:
print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)

print("\nColumns:")
print(train_df.columns.tolist())

Train shape: (560, 5)
Validation shape: (140, 5)

Columns:
['text', 'label_1', 'label_2', 'label_3', 'label_4']

Show before/after examples

In [4]:
show_examples(train_df, text_column="text", n=5)

Before: thanks status content fix warning review please message delay warning fix access report
After:  thanks status content fix warning review please message delay access report
----------------------------------------
Before: account system error reply content
After:  account system error reply content
----------------------------------------
Before: reply error info account content update notice notice reply fix problem
After:  reply error info account content update notice fix problem
----------------------------------------
Before: delay status access content access urgent reply thanks question
After:  delay status access content urgent reply thanks question
----------------------------------------
Before: reply please feedback feedback system delay request note
After:  reply please feedback system delay request note
----------------------------------------

Apply preprocessing to train and validation

In [5]:
train_clean = preprocess_dataframe(train_df, text_column="text")
val_clean = preprocess_dataframe(val_df, text_column="text")

train_clean.head()

,text,label_1,label_2,label_3,label_4,is_empty_after_clean
0,thanks status content fix warning review pleas...,1,1,1,1,False
1,account system error reply content,0,1,0,1,False
2,reply error info account content update notice...,0,1,0,0,False
3,delay status access content urgent reply thank...,0,0,0,0,False
4,reply please feedback system delay request note,0,0,1,0,False

Check empty texts after cleaning

In [6]:
print("Empty rows after cleaning:")
print("Train:", train_clean["is_empty_after_clean"].sum())
print("Validation:", val_clean["is_empty_after_clean"].sum())

Empty rows after cleaning:
Train: 0
Validation: 0

Check how many texts changed

In [7]:
changed_train = (train_df["text"].apply(clean_text) != train_clean["text"]).sum()
changed_val = (val_df["text"].apply(clean_text) != val_clean["text"]).sum()

print("Changed train texts:", changed_train)
print("Changed validation texts:", changed_val)

Changed train texts: 0
Changed validation texts: 0

Test repeated word cleaning

In [8]:
example = "feedback feedback system delay delay request"

print("Before:", example)
print("After: ", clean_text(example))

Before: feedback feedback system delay delay request
After:  feedback system delay request

Test save/load preprocessor

In [ ]:
# preprocessor = TextPreprocessor()

# preprocessor.save("../models/preprocessor.joblib")

# loaded = TextPreprocessor.load("../models/preprocessor.joblib")

# loaded.transform([
#     "URGENT!!! Fix fix error http://test.com"
# ])