In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root / "src"))

import pandas as pd

from member3_preprocess import *

In [3]:
train_df = pd.read_csv("../data/raw/dataset_C_train.csv")
val_df = pd.read_csv("../data/raw/dataset_C_val.csv")

train_df.head()

,text,label_1,label_2,label_3,label_4
0,thanks status content fix warning review pleas...,1,1,1,1
1,account system error reply content,0,1,0,1
2,reply error info account content update notice...,0,1,0,0
3,delay status access content access urgent repl...,0,0,0,0
4,reply please feedback feedback system delay re...,0,0,1,0

In [5]:
show_examples(train_df, text_col="text")

Before: thanks status content fix warning review please message delay warning fix access report
After:  thanks status content fix warning review please message delay warning fix access report
----------------------------------------
Before: account system error reply content
After:  account system error reply content
----------------------------------------
Before: reply error info account content update notice notice reply fix problem
After:  reply error info account content update notice reply fix problem
----------------------------------------
Before: delay status access content access urgent reply thanks question
After:  delay status access content access urgent reply thanks question
----------------------------------------
Before: reply please feedback feedback system delay request note
After:  reply please feedback system delay request note
----------------------------------------

In [6]:
train_clean = preprocess_dataframe(train_df, text_col="text")

train_clean.head()

,text,label_1,label_2,label_3,label_4,text_clean,is_empty_after_clean
0,thanks status content fix warning review pleas...,1,1,1,1,thanks status content fix warning review pleas...,False
1,account system error reply content,0,1,0,1,account system error reply content,False
2,reply error info account content update notice...,0,1,0,0,reply error info account content update notice...,False
3,delay status access content access urgent repl...,0,0,0,0,delay status access content access urgent repl...,False
4,reply please feedback feedback system delay re...,0,0,1,0,reply please feedback system delay request note,False

In [7]:
example = "feedback feedback system delay delay request"

print("Before:", example)
print("After: ", clean_text(example))

Before: feedback feedback system delay delay request
After:  feedback system delay request

In [8]:
run_sanity_checks(
    "../data/raw/dataset_C_train.csv",
    "../data/raw/dataset_C_val.csv"
)

============================================================
PREPROCESSING SANITY CHECKS
============================================================

Train shape: (560, 5)
Val shape: (140, 5)

Columns:
['text', 'label_1', 'label_2', 'label_3', 'label_4']

Before/After examples from train:
Before: thanks status content fix warning review please message delay warning fix access report
After:  thanks status content fix warning review please message delay warning fix access report
----------------------------------------
Before: account system error reply content
After:  account system error reply content
----------------------------------------
Before: reply error info account content update notice notice reply fix problem
After:  reply error info account content update notice reply fix problem
----------------------------------------
Before: delay status access content access urgent reply thanks question
After:  delay status access content access urgent reply thanks question
----------------------------------------
Before: reply please feedback feedback system delay request note
After:  reply please feedback system delay request note
----------------------------------------

Empty rows after cleaning:
Train: 0
Val:   0

Texts changed by preprocessing:
Train: 142
Val:   44

Repeated word test:
Before: feedback feedback system delay delay request
After:  feedback system delay request

Edge case tests:
'' -> ''
'   ' -> ''
None -> ''
'HELLO!!!' -> 'hello'
'Visit https://example.com' -> 'visit'
'<b>urgent problem</b>' -> 'urgent problem'
'error 404 warning' -> 'error warning'
'reply reply please please' -> 'reply please'

Sanity checks complete.

In [9]:
preprocessor = TextPreprocessor()

preprocessor.save("../models/preprocessor.joblib")

loaded = TextPreprocessor.load("../models/preprocessor.joblib")

loaded.transform([
    "URGENT!!! Fix fix error 404 http://test.com"
])

Preprocessor saved to: ../models/preprocessor.joblib
Preprocessor loaded from: ../models/preprocessor.joblib

['urgent fix error']